### ISSUE TITLE
libvirt inventory return  with  'No hosts matched'  

### ISSUE THREAD

**Issue by udomsak** [projectatomic/atomic-enterprise-ansible#13]
## Test command: 
```  ansible -i ./inventory/libvirt_generic.py --list-hosts all ```

## Result-command:

``` No hosts matched  ```

## Result return from 'libvirt_inventory' script : 

``` {"_meta": {"hostvars": {"node2": {"libvirt_uuid": "12aec8ae-dcf3-48a1-b9cb-6ef52b1be39b", "libvirt_status": "running", "ansible_ssh_host": "192.168.122.197", "libvirt_id": 83, "libvirt_name": "node2", "libvirt_ip_address": "192.168.122.197"}}}} ````

**Comment by cgwalters** [comment]
Hi, thanks for filing this issue.  Can you retest with the merged https://github.com/openshift/openshift-ansible and re-file there if it's still an issue?  Thanks!
