### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by sdodson** [projectatomic/atomic-enterprise-ansible#14]
If this project has been abandoned in favor of https://github.com/openshift/openshift-ansible we should note that in the readme.

**Comment by aveshagarwal** [comment]
@sdodson, yes that was just a stop gap measure for atomic enterprise, as everything has been merged in openshift-ansible, I dont think its needed any more.

**Comment by cgwalters** [comment]
https://github.com/projectatomic/atomic-enterprise-ansible/commit/f74ebc9fe2b91d8fe735f54b8320220721b86bfa

**Comment by sdodson** [comment]
Thanks for the quick action!
