### ISSUE TITLE
Fix inventory/byo/hosts

### ISSUE THREAD

**Issue by eparis** [projectatomic/atomic-enterprise-ansible#9]
This file has multiple issues.

- it has all sorts of 'usersys' entries in it. This obviously doesn't make sense.
- openshift_additional_repos= which we don't want
- it does not configure openshift_master_identity_providers= which we use in the training guide...
- I generally have no idea what those options do   :)

**Comment by aveshagarwal** [comment]
@eparis Either you can create a PR for this, or if its OK with you I can do a PR just to uncomment the required line.

**Comment by aveshagarwal** [comment]
@eparis has fixed the inventory host file with this PR https://github.com/projectatomic/atomic-enterprise-ansible/pull/10 .

**Comment by miminar** [comment]
Fixed.
